# [[redirects]]
#   from = "/assets/*"
#   to = "/static/:splat"
#   status = 200
#   force = true

[[redirects]]
  from = ""
  to = "https://benwiz.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/travelmap/*"
  to = "https://benwiz-travelmap.netlify.app/:splat/"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "https://benwiz-blog.netlify.app/:splat/"
  status = 200

[[redirects]]
  from = "/games/*"
  to = "https://benwiz-games.netlify.app/:splat/"
  status = 200

[[redirects]]
  from = "/games/*"
  to = "https://benwiz-games.netlify.app/drinking/:splat/"
  status = 200

[[redirects]]
  from = "/spyfall/*"
  to = "https://benwiz-spyfall.netlify.app/:splat/"
  status = 200

[[redirects]]
  from = "/taboo/*"
  to = "https://benwiz-taboo.netlify.app/:splat/"
  status = 200

[[redirects]]
  from = "/powerhour/*"
  to = "https://benwiz-powerhour.netlify.app/:splat/"
  status = 200

[[redirects]]
  from = "/codenames-trio/*"
  to = "https://benwiz-codenames-trio.netlify.app/:splat/"
  status = 200

[[redirects]]
  from = "/emacs/*"
  to = "https://benwiz-emacs.netlify.app/settings.html"
  status = 200

[[redirects]]
  from = "/scubahostels/*"
  to = "https://benwiz-scubahostels.netlify.app/:splat/"
  status = 200

[[redirects]]
  from = "/resume/*"
  to = "/resume.pdf"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"
