[[redirects]]
  from = "/travelmap/*"
  to = "https://benwiz-travelmap.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "https://benwiz-blog.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/games/*"
  to = "https://benwiz-games.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/spyfall/*"
  to = "https://benwiz-spyfall.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/taboo/*"
  to = "https://benwiz-taboo.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/powerhour/*"
  to = "https://benwiz-powerhour.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/codenames-trio/*"
  to = "https://benwiz-codenames-trio.netlify.app/:splat"
  status = 200

# Covering all my bases from an old config. Can remove this in not too distant future.

[[redirects]]
  from = "/games/spyfall"
  to = "https://benwiz.com/spyfall"

[[redirects]]
  from = "/games/taboo"
  to = "https://benwiz.com/taboo"

[[redirects]]
  from = "/games/powerhour"
  to = "https://benwiz.com/powerhour"

[[redirects]]
  from = "/games/codenames-trio"
  to = "https://benwiz.com/codenames-trio"
